/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 旅行一覧の取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"][];
                    };
                };
            };
        };
        put?: never;
        /** 旅行の作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TripCreate"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** 旅行の取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 旅行の削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 旅行の更新（名称・色・期間など） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TripUpdate"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/trips/{tripId}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** 旅行内のトラック一覧 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"][];
                    };
                };
            };
        };
        put?: never;
        /** トラックの開始（ライブ記録セッションの作成） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrackCreate"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{trackId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: components["parameters"]["TrackId"];
            };
            cookie?: never;
        };
        /** トラックの取得（メタ情報） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: components["parameters"]["TrackId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** トラックの状態更新（一時停止・終了） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: components["parameters"]["TrackId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "recording" | "paused" | "finished";
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tracks/{trackId}/points": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: components["parameters"]["TrackId"];
            };
            cookie?: never;
        };
        /** トラックの軌跡をGeoJSON（LineString）で取得 */
        get: {
            parameters: {
                query?: {
                    /** @description 表示用の簡略化許容誤差(m)。ズームに応じた間引きに使う */
                    simplify?: number;
                };
                header?: never;
                path: {
                    trackId: components["parameters"]["TrackId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功（GeoJSON Feature） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/geo+json": components["schemas"]["GeoJsonFeature"];
                    };
                };
            };
        };
        put?: never;
        /**
         * トラックポイントのバッチ投入（オフライン蓄積分の再送を含む）
         * @description モバイルはバッファした点をまとめて送る。サーバは last_point_at を更新し、 新規点が内包する行政区画を判定して未訪問なら visited_regions に記録する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: components["parameters"]["TrackId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TrackPointBatch"];
                };
            };
            responses: {
                /** @description 受理（取り込み結果サマリ） */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accepted?: number;
                            newlyVisitedRegionIds?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/import/gpx": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GPXファイルのインポート（トラックとして取り込み） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description 取込成功（作成されたトラック） */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Track"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 写真の取得（マップ表示用。全旅行横断・地点付き）
         * @description メインのマップ画面に写真ピンを表示するために使う。bboxやtripIdで絞り込める。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 表示範囲 [minLng,minLat,maxLng,maxLat]。カンマ区切り */
                    bbox?: string;
                    tripId?: string;
                    /** @description 地点が確定している写真のみ返すか */
                    hasLocation?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 写真アップロード用の署名付きURL発行
         * @description クライアントは返却されたURLへ直接 PUT して原本をR2へ置く
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example image/jpeg */
                        contentType: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            uploadUrl?: string;
                            objectKey?: string;
                            /** @description 有効秒数 */
                            expiresIn?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** 旅行の写真一覧（地点付き） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * アップロード済み写真のメタデータ登録
         * @description R2へPUT後に呼ぶ。EXIF/撮影時刻から地点を決定（無ければトラック突合）
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoRegister"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Photo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{trackId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: components["parameters"]["TrackId"];
            };
            cookie?: never;
        };
        /** トラックのコメント一覧（時系列の日記） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: components["parameters"]["TrackId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        /** トラックへのコメント追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackId: components["parameters"]["TrackId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photoId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoId: string;
            };
            cookie?: never;
        };
        /** 写真のコメント一覧（時系列の日記） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        /** 写真へのコメント追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** コメントの削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** コメントの更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/trips/{tripId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** 旅費の一覧 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"][];
                    };
                };
            };
        };
        put?: never;
        /** 旅費の追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpenseCreate"];
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}/expenses/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: components["parameters"]["TripId"];
            };
            cookie?: never;
        };
        /** 旅費の集計（費目別・合計） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripId: components["parameters"]["TripId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total?: number;
                            currency?: string;
                            byCategory?: {
                                category?: string;
                                amount?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expenseId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 旅費の削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    expenseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** 旅費の更新 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    expenseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpenseCreate"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 訪問済みエリアと統計の取得
         * @description トロフィー塗りつぶし用のGeoJSONと、訪問数・カバー率の統計を返す
         */
        get: {
            parameters: {
                query?: {
                    regionType?: "country" | "prefecture" | "city";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            stats?: {
                                visitedCount?: number;
                                totalCount?: number;
                                coverageRate?: number;
                            };
                            geojson?: components["schemas"]["GeoJsonFeatureCollection"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AIチャットセッションの作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        tripId?: string | null;
                        title?: string | null;
                    };
                };
            };
            responses: {
                /** @description 作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiChatSession"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * メッセージ送信（おすすめ経路を相談、応答はSSEでストリーミング）
         * @description 現在地・現在の旅行コンテキストを任意で付与できる。サーバは Claude API へ中継し、 text/event-stream で応答をストリーミングする。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                        context?: {
                            near?: components["schemas"]["LngLat"];
                            /** Format: uuid */
                            tripId?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description SSEストリーム（assistantの応答） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 端末（APNsトークン）の登録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example ios */
                        platform: string;
                        apnsToken: string;
                    };
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 端末の登録解除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code?: string;
            message?: string;
        };
        /** @description [経度, 緯度] の順（GeoJSON準拠） */
        LngLat: {
            lng?: number;
            lat?: number;
        };
        GeoJsonFeature: {
            /** @example Feature */
            type?: string;
            geometry?: Record<string, never>;
            properties?: Record<string, never>;
        };
        GeoJsonFeatureCollection: {
            /** @example FeatureCollection */
            type?: string;
            features?: components["schemas"]["GeoJsonFeature"][];
        };
        Trip: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /** @example #E8833A */
            color?: string;
            /** Format: date */
            startedOn?: string | null;
            /** Format: date */
            endedOn?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        TripCreate: {
            name: string;
            description?: string | null;
            color: string;
            /** Format: date */
            startedOn?: string | null;
            /** Format: date */
            endedOn?: string | null;
        };
        TripUpdate: {
            name?: string;
            description?: string | null;
            color?: string;
            /** Format: date */
            startedOn?: string | null;
            /** Format: date */
            endedOn?: string | null;
        };
        Track: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tripId?: string;
            /** @enum {string} */
            source?: "live" | "gpx";
            /** @enum {string} */
            status?: "recording" | "paused" | "finished";
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            /** Format: date-time */
            lastPointAt?: string | null;
            pointCount?: number;
        };
        TrackCreate: {
            /**
             * @default live
             * @enum {string}
             */
            source: "live" | "gpx";
            /** Format: date-time */
            startedAt?: string;
        };
        TrackPoint: {
            lng: number;
            lat: number;
            elevationM?: number | null;
            speedMps?: number | null;
            accuracyM?: number | null;
            /** Format: date-time */
            recordedAt: string;
        };
        TrackPointBatch: {
            points: components["schemas"]["TrackPoint"][];
        };
        Photo: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tripId?: string;
            lng?: number | null;
            lat?: number | null;
            /** @enum {string} */
            locationSource?: "exif" | "matched" | "unknown";
            /** Format: date-time */
            takenAt?: string | null;
            objectKey?: string;
            /** Format: uri */
            thumbnailUrl?: string | null;
            width?: number | null;
            height?: number | null;
        };
        PhotoRegister: {
            objectKey: string;
            /** Format: date-time */
            takenAt?: string | null;
            lng?: number | null;
            lat?: number | null;
            width?: number | null;
            height?: number | null;
            exif?: Record<string, never> | null;
        };
        Expense: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tripId?: string;
            category?: string;
            amount?: number;
            /** @example JPY */
            currency?: string;
            description?: string | null;
            /** Format: date-time */
            spentAt?: string;
        };
        ExpenseCreate: {
            category: string;
            amount: number;
            currency: string;
            description?: string | null;
            /** Format: date-time */
            spentAt: string;
        };
        AiChatSession: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tripId?: string | null;
            title?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        Comment: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            targetType?: "track" | "photo";
            /** Format: uuid */
            targetId?: string;
            body?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CommentCreate: {
            body: string;
        };
        Device: {
            /** Format: uuid */
            id?: string;
            platform?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: {
        /** @description リクエスト不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TripId: string;
        TrackId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
